-- Generated by Data Reliability Agent
-- Column: billing_address_line2
-- Root cause: The schema change on 'billing_address_line2' may lead to inconsistencies across multiple PowerBI pages and reports relying on the 'order_details' table.
-- Recommended fix: Conduct a thorough impact analysis and testing across all affected PowerBI pages and the report to ensure proper handling of the schema change.
-- Full column list sourced live from DataHub schema metadata
--
-- This is the proposed fix to the order_details dbt model itself.
-- It would replace the model's current SELECT statement, so the fix
-- happens before the table is built -- not as a separate step
-- inserted between the table and PowerBI.

{{ config(materialized='view') }}

select
billing_address_line1,  
COALESCE(billing_address_line2, '') AS billing_address_line2,  
billing_country,  
billing_region,  
billing_town_city,  
billing_zipcode,  
category_id,  
category_name,  
condition,  
cost_of_delivery,  
cust_email,  
cust_first_name,  
cust_last_name,  
customer_class,  
customer_id,  
delivery_status,  
delivery_type,  
discount_amount,  
discount_percent,  
dispatch_date,  
estimated_delivery,  
gift_wrap,  
line_item_id,  
line_total,  
list_price,  
order_date,  
order_id,  
order_mode,  
order_status,  
order_total,  
payment_method_code,  
phone_number,  
product_description,  
product_id,  
product_name,  
product_status,  
promotion_description,  
promotion_id,  
promotion_name,  
quantity,  
quantity_on_hand,  
return_date,  
return_status,  
shipping_address_line1,  
shipping_address_line2,  
shipping_country,  
shipping_region,  
shipping_town_city,  
shipping_zipcode,  
stock_status,  
unit_price,  
updated_at,  
wait_till_complete_yn,  
warehouse_id,  
warehouse_name
from {{ ref('order_details') }}  -- adjust to your actual upstream model/source name
